document.writeln("<style type=\'text/css\'>");
document.writeln("    .col-xs-3{padding: 0;overflow: hidden; white-space:nowrap; word-break:break-all; text-align: center; background-color: #000; }");
document.writeln("    .col-xs-3 a{font-size:12px;color: #fff}");
document.writeln("</style>");
document.writeln("<div class=\'row\' id=\'showTXtAd\' style=\'margin-right: 0; margin-left: 0; display: none;\'>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>无毛萝莉自拍</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>AV名模绝美身材</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>韩国美女自慰</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>和姐姐做爱</a></div>");
document.writeln("");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>黑人操白人B高清</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>16岁幼女视频</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>口交勾引爸爸</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>明星淫荡乱伦</a></div>");
document.writeln("");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>人与动物牲交</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>狂操处女小淫逼</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>诱惑寂寞少妇</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>05后自拍</a></div>");
document.writeln("");
//document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>高中生无套射精</a></div>");
//document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>色老师插学生</a></div>");
//document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>吊带丝袜高跟</a></div>");
//document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>国产情侣偷拍</a></div>");
//document.writeln("");
//document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>性感巨乳萝莉</a></div>");
//document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>岛国无码av</a></div>");
//document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>手指插嫩穴</a></div>");
//document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/4se-txt.php\'>边看片边操表妹</a></div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("    function isMobileROW(){");
document.writeln("        if(/(iPhone|iPad|iPod|iOS|Android)/i.test(navigator.userAgent)) {");
document.writeln("            return true;");
document.writeln("        }");
document.writeln("        return false;");
document.writeln("    }");
document.writeln("    $(document).ready(function(){");
document.writeln("        if(isMobileROW()){");
document.writeln("            $(\'#showTXtAd\').show();");
document.writeln("        }");
document.writeln("    });");
document.writeln("</script>");