document.writeln("<style type=\'text/css\'>");
document.writeln("    .col-xs-3{padding: 0;overflow: hidden; white-space:nowrap; word-break:break-all; text-align: center; background-color: #336699; }");
document.writeln("    .col-xs-3 a{font-size:14px;color: #ffffff}");
document.writeln("</style>");
document.writeln("<div class=\'row\' id=\'showTXtAd\' style=\'margin-right: 0; margin-left: 0; display: none;\'>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=1\'>内射</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=2\'>口交</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=3\'>少女</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=4\'>玩具</a></div>");
document.writeln("");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=5\'>自慰</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=6\'>户外</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=7\'>颜射</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=8\'>其他</a></div>");
document.writeln("");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=9\'>乳交</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=10\'>三人交</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=11\'>捆绑</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=12\'>群p</a></div>");
document.writeln("");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=13\'>熟母</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=14\'>手淫</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=15\'>重口</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=16\'>素人</a></div>");
document.writeln("");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=17\'>指交</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=18\'>肛交</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=19\'>爆射</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_self\' href=\'/index.php?c1=5&c2=20\'>口爆</a></div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("    function isMobileROW(){");
document.writeln("        if(/(iPhone|iPad|iPod|iOS|Android)/i.test(navigator.userAgent)) {");
document.writeln("            return true;");
document.writeln("        }");
document.writeln("        return false;");
document.writeln("    }");
document.writeln("    $(document).ready(function(){");
document.writeln("        if(isMobileROW()){");
document.writeln("            $(\'#showTXtAd\').show();");
document.writeln("        }");
document.writeln("    });");
document.writeln("</script>");