document.writeln("<style type=\'text/css\'>");
document.writeln("    .col-xs-3{padding: 0;overflow: hidden; white-space:nowrap; word-break:break-all; text-align: center; background-color: #000; }");
document.writeln("    .col-xs-3 a{font-size:12px;color: #fff}");
document.writeln("</style>");
document.writeln("<div class=\'row\' id=\'showTXtAd\' style=\'margin-right: 0; margin-left: 0; display: none;\'>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>内射清纯萝莉</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>和嫂子偷情⚤</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>淫荡少女做爱</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>少女足交视频💋</a></div>");
document.writeln("");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>饥渴的学妹😍</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>极品白🐅虎穴</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>重口味A片👅</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>网曝门系列</a></div>");
document.writeln("");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>小鸟酱大尺度</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>👩‍🏫老师的诱惑</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>美鲍嫩穴自拍</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>高清成人网站</a></div>");
document.writeln("");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>🔥SWAG嫩模🔥</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>全球毛片基地</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>天天撸一撸👐</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>情趣内衣勾引</a></div>");
document.writeln("");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>嫩模援交曝光</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>极品国外幼女</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>无套直射妈妈</a></div>");
document.writeln("    <div class=\'col-xs-3\'><a target=\'_blank\' href=\'https://moon-test.com:7788/jn-txt.php\'>💞操女大学生</a></div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("    function isMobileROW(){");
document.writeln("        if(/(iPhone|iPad|iPod|iOS|Android)/i.test(navigator.userAgent)) {");
document.writeln("            return true;");
document.writeln("        }");
document.writeln("        return false;");
document.writeln("    }");
document.writeln("    $(document).ready(function(){");
document.writeln("        if(isMobileROW()){");
document.writeln("            $(\'#showTXtAd\').show();");
document.writeln("        }");
document.writeln("    });");
document.writeln("</script>");